require File.expand_path('lib/foreman_ai_templates/version', __dir__)

Gem::Specification.new do |s|
  s.name        = 'foreman_ai_templates'
  s.version     = ForemanAiTemplates::VERSION
  s.metadata    = { 'is_foreman_plugin' => 'true' }
  s.license     = 'GPL-3.0'
  s.authors     = ['Oleh Fedorenko']
  s.email       = ['ofedoren@redhat.com']
  s.homepage    = 'https://github.com/theforeman/foreman_ai_templates'
  s.summary     = 'ERB Templates generated by AI to be used in Foreman'
  s.description = 'Plugin uses AI to generate various ERB templates to be used in Foreman.'

  s.files = Dir['{app,config,db,lib,locale,webpack}/**/*'] + ['LICENSE', 'Rakefile', 'README.md', 'package.json']
  s.test_files = Dir['test/**/*'] + Dir['webpack/**/__tests__/*.js']

  s.required_ruby_version = '>= 2.7', '< 4'

  s.add_development_dependency 'rdoc'

  s.add_dependency 'ruby-openai'
end
